using namespace System.IO

PARAM (
    [Parameter(Mandatory = $true)][ValidateNotNull()][DirectoryInfo]$Directory
)

# TODO: /account
#           GET /requestable/hardware
#           GET /requests

@"
// Generated by account.ps1 at $(Get-Date -Format 'G')
namespace SnipeSharp.Tests
{
    internal static partial class Resources
    {
        internal static class Account
        {
            internal const string Requests = "./Resources/Integration/GET_account_requests.json";
            internal const string RequestableHardware = "./Resources/Integration/GET_account_requestable_hardware.json";
        }
    }
}

"@ -replace "`r`n", "`n" | Out-File -Encoding 'UTF8' -NoNewline -LiteralPath (Join-Path -Path $Directory.FullName -ChildPath 'Resources.Account.cs')
